services:

  hdfs-namenode:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./hadoop/dfs/namenode:/hadoop/dfs/namenode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-namenode.sh:/start-namenode.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-namenode:9870/"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/bash", "-c", "/start-namenode.sh"]
    restart: always
    networks:
      - spark-network

  hdfs-datanode:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-datanode
    hostname: hdfs-datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    depends_on:
      hdfs-namenode:
        condition: service_healthy
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./hadoop/dfs/datanode:/hadoop/dfs/datanode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-datanode.sh:/start-datanode.sh
    command: ["/bin/bash", "-c", "/start-datanode.sh"]
    restart: always
    networks:
      - spark-network

  spark-master:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-master
    hostname: spark-master
    restart: always
    ports:
      - "7077:7077"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_DAEMON_USER=spark
      - SPARK_DAEMON_GROUP=spark
    volumes:
      - ./spark/lib/iceberg-spark-runtime-3.5_2.12-1.8.1.jar:/opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-worker
    hostname: spark-worker
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_DAEMON_USER=spark
      - SPARK_DAEMON_GROUP=spark
    volumes:
      - ./spark/lib/iceberg-spark-runtime-3.5_2.12-1.8.1.jar:/opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
    ipam:
      config:
        - subnet: 172.15.0.0/16